### ISSUE TITLE
Feature: Atto editor plugin

### ISSUE THREAD

**Issue by agwells** [catalyst/moodle-tool_trigger#10]
As @danmarsden  touched upon here: https://github.com/catalyst/moodle-tool_trigger/issues/6#issuecomment-389317576

Some of the action/trigger steps have the workflow author writing up a big template text (an email body, for instance), and putting placeholders into it which will get replaced by the event data and lookup data. It'd be useful for workflow authors if there were a plugin to the Atto richtext editor, which gave you a button to list all the currently known placeholders in the current workflow, to make it easier to insert them.

**Comment by brendanheywood** [comment]
This has come up on my radar, I think we pick this up shortly
