### ISSUE TITLE
content-type is not send when json encode is selected

### ISSUE THREAD

**Issue by rovebd** [catalyst/moodle-tool_trigger#117]
Hi.

The content-type = application/json header is not set when json encode checkbox is select in http post.

We fixed it in classes/steps/actions/http_post_action_step.php, execute() method

[contenttype.diff.gz](https://github.com/catalyst/moodle-tool_trigger/files/5050731/contenttype.diff.gz)

Regards,
Roberto.

**Comment by mattporritt** [comment]
Headers need to be added explicitly in the "Headers " filed of the HTTP post form
