### ISSUE TITLE
HTTP trigger step

### ISSUE THREAD

**Issue by agwells** [catalyst/moodle-tool_trigger#12]
There's an outline of an "HTTP POST" step right now, but it still needs to have its "execute" method implemented.

**Comment by mattporritt** [comment]
Make sure we use Guzzle as the HTTP client. It’s much better than the standard Moodle or PHP cURL libs and allows for good test integration. We’ve used it in a few plugins now.
Have a look at search_azure for an implementation example. Should be able to copy/paste most of it.

**Comment by agwells** [comment]
Okay, I've implemented a Guzzle-using HTTP POST trigger step.
