### ISSUE TITLE
User Lookup fails due to missing fields

### ISSUE THREAD

**Issue by joewickert** [catalyst/moodle-tool_trigger#144]
Hi,

Had issues with user lookups on version  2021030400 so updated to  2021030401.

Moodle version 3.11 (Build: 20210517)

Got this error on user lookups.

```
Debug info:
Unknown column 'icq' in 'field list'
SELECT id,auth,confirmed,policyagreed,deleted,suspended,mnethostid,username,idnumber,firstname,lastname,email,emailstop,icq,skype,yahoo,aim,msn,phone1,phone2,institution,department,address,city,country,lang,calendartype,theme,timezone,firstaccess,lastaccess,lastlogin,currentlogin,lastip,picture,url,description,descriptionformat,mailformat,maildigest,maildisplay,autosubscribe,trackforums,timecreated,timemodified,trustbitmask,imagealt,lastnamephonetic,firstnamephonetic,middlename,alternatename FROM mdl_user WHERE id = ?
[array (
  0 => '3',
)]
Backtrace:
* line 1273 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 1671 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
* line 1643 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
* line 1622 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 129 of /lib/classes/user.php: call to moodle_database->get_record()
* line 140 of /admin/tool/trigger/classes/steps/lookups/user_lookup_step.php: call to core_user::get_user()
* line 76 of /admin/tool/trigger/classes/helper/processor_helper.php: call to tool_trigger\steps\lookups\user_lookup_step->execute()
* line 199 of /admin/tool/trigger/classes/task/process_workflows.php: call to tool_trigger\task\process_workflows->execute_step()
* line 142 of /admin/tool/trigger/classes/task/process_workflows.php: call to tool_trigger\task\process_workflows->process_item()
* line 91 of /admin/tool/trigger/classes/task/process_workflows.php: call to tool_trigger\task\process_workflows->process_queue()
* line 253 of /lib/cronlib.php: call to tool_trigger\task\process_workflows->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()
```
It seems that Moodle no longer installs with a few outdated user social fields. (icq,skype,url).

related issue https://tracker.moodle.org/browse/MDL-28452

But classes/steps/lookups/user_lookup_step.php includes them in queries.

Deleting them solves the issue for me.

Removed:
```
            'icq',
            'skype',
            'yahoo',
            'aim',
            'msn',
            'url'
```

I guess this is only for new installs as upgrades will retain existing social fields.

But maybe needs to check if columns exist before searching?

Thanks for the module

**Comment by durzo** [comment]
we are also experiencing this issue on 3.11

**Comment by jtsafran** [comment]
Looks like the new new 3.11 branch for this plugin as noted in the README https://github.com/catalyst/moodle-tool_trigger#readme fixes this issue in the following commit https://github.com/catalyst/moodle-tool_trigger/commit/23c2103e24dbf0a03c8e53d28971d716b5ed06a9

Branch at https://github.com/catalyst/moodle-tool_trigger/tree/MOODLE_311

I haven't had a chance to test it, yet, but wanted to update the ticket for those following along.

**Comment by JoaoCaldasCosta** [comment]
> Hi,
> 
> Had issues with user lookups on version 2021030400 so updated to 2021030401.
> 
> Moodle version 3.11 (Build: 20210517)
> 
> Got this error on user lookups.
> 
> ```
> Debug info:
> Unknown column 'icq' in 'field list'
> SELECT id,auth,confirmed,policyagreed,deleted,suspended,mnethostid,username,idnumber,firstname,lastname,email,emailstop,icq,skype,yahoo,aim,msn,phone1,phone2,institution,department,address,city,country,lang,calendartype,theme,timezone,firstaccess,lastaccess,lastlogin,currentlogin,lastip,picture,url,description,descriptionformat,mailformat,maildigest,maildisplay,autosubscribe,trackforums,timecreated,timemodified,trustbitmask,imagealt,lastnamephonetic,firstnamephonetic,middlename,alternatename FROM mdl_user WHERE id = ?
> [array (
>   0 => '3',
> )]
> Backtrace:
> * line 1273 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
> * line 1671 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
> * line 1643 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
> * line 1622 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
> * line 129 of /lib/classes/user.php: call to moodle_database->get_record()
> * line 140 of /admin/tool/trigger/classes/steps/lookups/user_lookup_step.php: call to core_user::get_user()
> * line 76 of /admin/tool/trigger/classes/helper/processor_helper.php: call to tool_trigger\steps\lookups\user_lookup_step->execute()
> * line 199 of /admin/tool/trigger/classes/task/process_workflows.php: call to tool_trigger\task\process_workflows->execute_step()
> * line 142 of /admin/tool/trigger/classes/task/process_workflows.php: call to tool_trigger\task\process_workflows->process_item()
> * line 91 of /admin/tool/trigger/classes/task/process_workflows.php: call to tool_trigger\task\process_workflows->process_queue()
> * line 253 of /lib/cronlib.php: call to tool_trigger\task\process_workflows->execute()
> * line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
> * line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
> * line 178 of /admin/cli/cron.php: call to cron_run()
> ```
> 
> It seems that Moodle no longer installs with a few outdated user social fields. (icq,skype,url).
> 
> related issue https://tracker.moodle.org/browse/MDL-28452
> 
> But classes/steps/lookups/user_lookup_step.php includes them in queries.
> 
> Deleting them solves the issue for me.
> 
> Removed:
> 
> ```
>             'icq',
>             'skype',
>             'yahoo',
>             'aim',
>             'msn',
>             'url'
> ```
> 
> I guess this is only for new installs as upgrades will retain existing social fields.
> 
> But maybe needs to check if columns exist before searching?
> 
> Thanks for the module

How/where to I remove those fields? icq, skype,... Thanks in advance

**Comment by joewickert** [comment]
If you are on the Master branch they are in:

classes/steps/lookups/user_lookup_step.php

If you install the 3.11 branch the issue should be fixed, I haven't tested though.

**Comment by dmitriim** [comment]
This has been fixed in MOODLE_311_STABLE branch.
