### ISSUE TITLE
Moodle 3.11 will require change to user fields

### ISSUE THREAD

**Issue by cladelpino** [catalyst/moodle-tool_trigger#155]
Fields  icq,aim,msn,url,yahoo,skype were "deprecated" in Moodle 3.11, and they are hard-coded in this plugin in user_lookup_step.php 

For a quick fix, comment them out from the $stepfields array.

**Comment by dmitriim** [comment]
Duplicate of https://github.com/catalyst/moodle-tool_trigger/issues/144

**Comment by JoaoCaldasCosta** [comment]
> Fields icq,aim,msn,url,yahoo,skype were "deprecated" in Moodle 3.11, and they are hard-coded in this plugin in user_lookup_step.php
> 
> For a quick fix, comment them out from the $stepfields array.

How/where can I do this?
I am trying to put this to work and I can do the course lookup but I always get an error on the user lookup, I suppose it is the same issue you reported

**Comment by dmitriim** [comment]
@JoaoCaldasCosta  please switch to MOODLE_311_STABLE branch. The issue has been fixed there.
