### ISSUE TITLE
Make Plugin GDPR compliant

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-tool_trigger#16]
Add the boilerplate GDPR API code to plugin

**Comment by agwells** [comment]
As discussed in chat: The current privacy profile of the plugin, is that it can export user data to external sources (via the email and HTTP steps), but it doesn't store user data. I'll implement the GDPR API accordingly.

**Comment by agwells** [comment]
@mattporritt, @danmarsden Can you take a look and see if the privacy data I've added looks correct?

**Comment by mattporritt** [comment]
looks good to me
