### ISSUE TITLE
Feature: In the workflow step setup, show the user what datafields are available

### ISSUE THREAD

**Issue by agwells** [catalyst/moodle-tool_trigger#17]
This is the biggest thing that would be needed, to make it less painful to write new workflows. Currently we have the "datafield" system that lets you access data from the event, and data added by lookup steps, and add it into templates with {placeholder} tags. But, there's no system to tell you what datafield names are available.

Here are the main areas the data comes from.

1. "Standard" event properties. These are defined by the Moodle "Event 2" API: https://docs.moodle.org/dev/Event_2#Properties . Some are optional, and some have different meanings for different event types.
2. "Other" event properties. Events can have an "other" field which contains additional data. There is *no* machine-readable definition for this, although it is recommended to describe it in the event class's phpdocs.
3. "Logextra" event fields. These are fields added when a logstore serializes an event. We're using the `buffered_writer` logstore trait, so we get these even though we're not actually a full-on logstore plugin. There are just three of these: "origin" (i.e. "web"), IP address, and realuserid (if the user was masquerading)
4. Fields added by lookup steps. Currently we don't require the lookup step to indicate what datafields it's going to add (until it actually runs). But we could make this into a requirement.

Unfortunately, the Moodle Event 2 API doesn't require events to be self-describing in a machine-readable way, like most other Moodle APIs do. The only machine-readable means to find out the optional and "other" fields of an event type is to inspect an instance of the event class. And unfortunately, there's also no safe way to instantiate an event class without specific knowledge about the data it needs, because event classes can include a `validate_data()` method, which throws an exception if the data fields provided are incorrect or incomplete for that event type!

So our options seem to be: 1) Make reasonable guesses at the fields in use, by inspecting the class's source code file; 2) ask the user to trigger a sample event which we can capture and inspect; or 3) manually write up a description of every event type in Moodle core (and don't worry about plugins).

**Comment by agwells** [comment]
See also #34, "Draft mode", which includes the ability to "capture" and inspect sample events.

**Comment by agwells** [comment]
Another idea: Use the Moodle core unit tests to generate and capture sample events.

There should be at least one unit test that generates an event of each type. If we could capture those, we could use them to infer the "other" fields, and optional fields, of each core event type, and put that into a dictionary of events that we ship with the plugin.

I haven't looked into the guts of the Moodle unit testing setup, so I'm not sure how complicated this would be. It'd probably be easiest to do by patching Moodle core's event lib so that when an event is created, it serializes it and commits it to a database (outside the testing DB).

**Comment by mattporritt** [comment]
This functionality has now been added, the master branch and documentation updated.
