### ISSUE TITLE
Send student an email when their quiz attempt has been fully graded

### ISSUE THREAD

**Issue by Dyegov** [catalyst/moodle-tool_trigger#180]
Hi there,

I would like some help on how to automatically send the student an email notifying them that their quiz attempt has been fully graded. All my quizzes contain a combination of automatically graded questions (MCQs), and some open ended ones (Essays) which need to first be manually graded by a teacher.

What would be the correct Moodle event to watch out for?

Thanks!

**Comment by Peterburnett** [comment]
This is very much dependent on the setup of the course. I can't really give a conclusive answer, as its dependent on what you call the final grade, etc if a teacher goes back and updates a grade, then the final time email would be wrong. So this is something that you need to make a business decision on, and then create a workflow based on that.

**Comment by Peterburnett** [comment]
see lib/classes/event/ for a list of all of the event classes in core, and the individual plugin classes for plugin events

**Comment by dmitriim** [comment]
Hi @Dyegov 
Your question is not directly related to tool_trigger. Please try asking for help in Forums https://moodle.org/mod/forum/
Cheers!
