### ISSUE TITLE
User lookup fails

### ISSUE THREAD

**Issue by JoaoCaldasCosta** [catalyst/moodle-tool_trigger#183]
Hi, 
I am trying to implement an automatic email to be sent to students when a quiz is manually graded (my quizzes have a mix of auto-graded and manual graded questions).
The process is triggered and the email is sent when I only have:
 
![image](https://user-images.githubusercontent.com/20328912/165865936-3ec782ae-4903-46e2-8acb-dbcbab73d772.png)

But it fails in student lookup when I have:
 
![image](https://user-images.githubusercontent.com/20328912/165865927-0842e8f1-be8a-41a7-90d9-dc58b6e4718b.png)

Event description:
'User graded'
'The user with id \'-1\' updated the grade with id \'491\' for the user with id \'25\' for the grade item with id \'40\'.'
Step ID: 56
Step results:
'{
    "error": "Invalid parameter value detected"
}'

I am using Moodle 3.11.3+ (Build: 20211003) and event trigger MOODLE_311_STABLE (2022031100).

Any ideas on how to fix this?
Thanks in advance.

**Comment by dmitriim** [comment]
Probably you are using incorrect filed (assuming userid) from user_graded event when you looking up for a student. Try to use 'relateduserid' event field as "User id data field" for your step.
