### ISSUE TITLE
Add new trigger workflow form - allow existing trigger edit/move

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_trigger#2]
When you have added a number of workflow steps (triggers) to an existing workflow, clicking the "edit" link should allow that specific step to be edited.
you should also be able to reorder the steps (drag/drop or move handlers)

![triggereditmove](https://user-images.githubusercontent.com/362798/39661518-e41b9b2e-50a6-11e8-9245-3a419efc0bd9.png)

**Comment by danmarsden** [comment]
note when changing order of steps of a trigger that already exists (instead of just changing the order of a new trigger), "steporder" in the trigger table will need to be updated on save of the form.

**Comment by agwells** [comment]
Done! Now all the buttons work -- up, down, edit, and delete. Nothing is saved until you submit the main "edit workflow" form. Instead, changes are saved into a serialized list of step data in the hidden "Stepjson" form (the same as what we were already using for adding new steps).

When you submit the form successfully, the steps in the serialized list are compared to the workflow's steps in the database, and steps are inserted, updated, or deleted as necessary.

**Comment by danmarsden** [comment]
Great - thanks Aaron!
