### ISSUE TITLE
How to program own workflow steps?

### ISSUE THREAD

**Issue by fishfree** [catalyst/moodle-tool_trigger#213]
First to say, this plugin is so ingenious and flexible! Thanks very much!

Can we develop customised workflow steps inheritted from this plugin? There seems no such documentation.

**Comment by danmarsden** [comment]
great to hear you find it useful. Yes - if you have internal development capabilities, you can write your own workflow steps, however you will need to use the existing steps as examples on how to do this as we do not have any documentation on this that would help. Also make sure you take a look at our newer tool_dataflows plugin which expands on the ideas from the tool_trigger plugin.

If you don't have internal development capabilities and would like to fund improvements - feel free to reach out privately and we can provide information on our rates!
