### ISSUE TITLE
Feature: A step that executes Moodle webservice functions

### ISSUE THREAD

**Issue by agwells** [catalyst/moodle-tool_trigger#30]
Moodle has a large set of "webservice functions", which all do useful things and include detailed machine-readable descriptions: https://docs.moodle.org/dev/Web_services

It could be very useful to expose these through the plugin, because they do the same sorts of useful task our steps are likely to want to do, and they're defined in a machine-readable way.

The main obstacles that would need to be overcome:

1) There are a **lot** of webservice functions. Around 500. And not all of them will be useful for the kinds of tasks workflows are probably going to do. (For example some of them are designed to provide specific data to specific external services.) So we'd probably want to make them searchable.

2) Webservice functions are generally designed to run using the identity of a logged-in Moodle user account. Our plugin, on the other hand, runs as the generic "cron" user. So a webservice step would need to specify which user to run the step as.

**Comment by mattporritt** [comment]
I've been having a think about this. As webservices can essentially be actions, lookups (and possibly filters), I think it might be better to define webservices as there own step type.

Also in terms of who to run the user as, I agree defining who to run the user as (with a default to admin) Is probably going to be the best way. We'll need to figure how to do this in practice as we will likely be calling the webservice via the internal API

**Comment by brendanheywood** [comment]
+1 we just this this, in hindsight is seems like an obvious missing feature
