### ISSUE TITLE
Unable to edit saved triggers

### ISSUE THREAD

**Issue by daroz** [catalyst/moodle-tool_trigger#31]
Hello,
I've saved a few triggers and now I can't delete them. I can't see any edit icons under manage section. Probably I'm doing something wrong. Could you please help me? 
![screenshot](https://user-images.githubusercontent.com/5477262/41284874-e4b41a1e-6e3a-11e8-8699-8b7123dbffef.jpg)
My moodle is 3.5, plugin version 2018052500, php 7.1.

**Comment by mattporritt** [comment]
Hi @daroz 
Thanks for reporting this.  I'm having some trouble reproducing this on my end. In the Mange column you should see 3 icons to allow you to edit, delete and copy workflows. I can see from your screen shot that they are not there.

I'll try setting up the plugin on a fresh 3.5 using the same version as you have indicated and will let you know.

Any other information you could provide would be great. Are you setting the workflow up as a site admin or another user? Are using the default boost theme or another theme? Are you able to increase the site logging at /admin/settings.php?section=debugging and see if the logs show anything?
Also if you are able to are you able to inspect the manage column with your web browser tools to see if the elements are being rendered but not displayed for some reason.

Cheers,
Matt P

**Comment by daroz** [comment]
Hi @mattporritt,
thanks for your reply. I'm setting the workflow up as a site admin. I've tried using adaptable, clean, boost theme and got the same result. After turning debugging it seems there are no errors. Action icons in manage column for some reason are set to invisible (in css). What should I put in custom css to make them visible?

**Comment by danmarsden** [comment]
@daroz - are you using the latest code from github here or are you using a version from the plugins db?

There is some Javascript that is supposed to un-hide that div that might not be running - can you also open up your web developer console in the web browser to see if any errors are showing in the web browser console?

You could also temporarily try turning off the "cache javascript" setting and see if that helps (don't leave that turned off on a prod server - it just might help us diagnose the problems)

**Comment by mattporritt** [comment]
@daroz 
I'm still not sure what is going on with the hidden icons. I installed the same version of the plugin on a fresh 3.5 with same php version etc. I haven't been able to replicate the issue. It does sound like it is conflicting with something else.  I'm not sure what that javascript error is in the console, but I'm not seeing it.

In terms of getting the available placeholders, this is something we are working on making easier. One of the issues is that Moodle doesn't define the fields that an event can provide, like the way webservices do.  

In the short term you can add the cron log action step to the workflow. Then when the event triggers the workflow the available fields will be dumped to the log.

**Comment by daroz** [comment]
Matt, Dan thank you so much for solving this problem. Now everything works.
