### ISSUE TITLE
 syntax error, unexpected '$string' (T_VARIABLE) during installtion

### ISSUE THREAD

**Issue by fishfree** [catalyst/moodle-tool_trigger#38]
Happened on 2018-08-12, the master branch.

**Comment by danmarsden** [comment]
can you please provide the full error message you received? - typically it refers to a line number and file. Also what version of Moodle are you using and what version of PHP?

**Comment by fishfree** [comment]
Moodle 3.4 stable & PHP 7.1.9

**Comment by danmarsden** [comment]
As I previously requested can you also provide the full error message you received, including line numbers/files that generated this.

**Comment by danmarsden** [comment]
(you may need to increase the debugging level set in your moodle site to "developer" to see the full trace.)

**Comment by fishfree** [comment]
@danmarsden Thank you for your tip. It turned out that another plugin A caused the error. During the installtaion of tool_trigger, I modified the code of A and left a grammer error. Sorry for my mistake!
