### ISSUE TITLE
How to send a HTTP JSON POST action? (need more detailed documentation)

### ISSUE THREAD

**Issue by fishfree** [catalyst/moodle-tool_trigger#39]
I succeeded in sending a x-www-form-urlencoded HTTP POST action, but cannot get a JSON POST working.
I have 3 questions:

1. How to input multiple headers? I tried one header one line, and tried seperating with comma in the same line, both failed.
2. How to input a JSON string as Parameters? Because a JSON string itselft is bracketed, then how to deal with field placeholders?
3. In which case, it is necessary to enable JSON encode parameters?

![httppostjsonaction](https://user-images.githubusercontent.com/1741341/44197084-46bcfd80-a170-11e8-9176-8e3ba7049f23.png)

**Comment by mattporritt** [comment]
Hi @fishfree yeah the documentation is pretty awful for this at the moment. I'll post an example soon, that will answer your questions.

**Comment by mattporritt** [comment]
Hi @fishfree 
To answer your questions:
1. One header per line should work
2 &3. JSON output support isn't great at the moment. To output JSON you need to form encode the data you want to send then enable `JSON encode parameters`.

The below screen shots show how to set up an example to send the data in JSON. I've also included a screen shot of what was received from the test Requestbin instance I used.

![image](https://user-images.githubusercontent.com/7369127/44314224-9d208980-a459-11e8-8882-73091ad20f29.png)

![image](https://user-images.githubusercontent.com/7369127/44314226-a4479780-a459-11e8-8f2e-820d6c3afbc0.png)

**Comment by fishfree** [comment]
@mattporritt Thank you! It works now. BTW: I think it's better using single bracket instead of double brackets in Parameters.
