### ISSUE TITLE
add validation to trigger form when no steps have been added

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_trigger#4]
It should not be possible for a Workflow to be added that does not have any workflow steps.

we need to add validation to the main form to fail validation when no workflow steps have been added.

**Comment by danmarsden** [comment]
that is probably enough, if we get bad data in there, I'd expect it's because the step form validation needs more improvement. Just push it through when you're ready!

**Comment by agwells** [comment]
Okay, merged!
