### ISSUE TITLE
Feature: add an ability to trigger a workflow synchronously 

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_trigger#84]
Add an ability to trigger a workflow synchronously when event happened. 
Probably a new checkbox in the Workflow form.

**Comment by mattporritt** [comment]
This feature should default to off, as we want to process most calls async (so we don't block the user).

**Comment by mattporritt** [comment]
field: "enable real time processing"
help: "When enabled this workflow will be triggered synchronously as part of the event. Use caution when enabling as long running workflows will block the user interface."
