### ISSUE TITLE
Feature: add a new action Role allocation 

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_trigger#85]
We should be able to allocate a role on an event. 

 * drop down list of roles in the form 
 * user id field  
 * form validation should check if a role is in different to system context level and if so, then force to provide context id (s)
* then validate if correct context ids provided.

**Comment by mattporritt** [comment]
This issue might be related: https://github.com/catalyst/moodle-tool_trigger/issues/27

**Comment by dmitriim** [comment]
Fixed as part of #86
