### ISSUE TITLE
Moodle 3.7 on Oracle

### ISSUE THREAD

**Issue by hmgp** [catalyst/moodle-tool_trigger#93]
Hi! After instalation when I try to go to the Manage part of the plugin I get this error:

Error reading from database

More information about this error
Debug info: ORA-00923: FROM keyword not found where expected
SELECT *
FROM (
select
*,
(select count(*) from m_tool_trigger_steps s where s.workflowid = w.id) as numsteps
from m_tool_trigger_workflows w
order by name ASC)
WHERE rownum <= :o_oracle_num_rows
[array (
'o_oracle_num_rows' => 100,
)]
Error code: dmlreadexception
Stack trace:

    line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 277 of /lib/dml/oci_native_moodle_database.php: call to moodle_database->query_end()
    line 1179 of /lib/dml/oci_native_moodle_database.php: call to oci_native_moodle_database->query_end()
    line 144 of /admin/tool/trigger/classes/workflow_manager.php: call to oci_native_moodle_database->get_records_sql()
    line 182 of /admin/tool/trigger/classes/output/manageworkflows/renderable.php: call to tool_trigger\workflow_manager::get_workflows_paginated()
    line 1670 of /lib/tablelib.php: call to tool_trigger\output\manageworkflows\renderable->query_db()
    line 64 of /admin/tool/trigger/classes/output/manageworkflows/renderer.php: call to table_sql->out()
    line 49 of /admin/tool/trigger/classes/output/manageworkflows/renderer.php: call to tool_trigger\output\manageworkflows\renderer->render_table()
    line 462 of /lib/outputrenderers.php: call to tool_trigger\output\manageworkflows\renderer->render_renderable()
    line 50 of /admin/tool/trigger/manage.php: call to plugin_renderer_base->render()

I think it's because I'm on an Oracle database. What can I do to solve this?

Thank you.

**Comment by danmarsden** [comment]
Thanks for the report.

As with Moodle core - use of Oracle is "supported" but at your own risk. Fixes for Oracle issues in Moodle core are 100% reliant on community contributions - we don't run Oracle here either - feel free to help us work on this by submitting a pull request.

thanks!

**Comment by mattporritt** [comment]
Closing
